<a href="https://colab.research.google.com/github/Akshiiiita/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy- Numerical Python

In [1]:
import numpy as np

List vs numpy time taken

In [2]:
from time import process_time

Time taken by list

In [4]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()

print(end_time-start_time)

0.0013917839999999515


In [5]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()

print(end_time-start_time)

0.0007625190000002391


Numpy Arrays

In [6]:
# list
list1 = [1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [7]:
np_array = np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [8]:
# creating 1 d array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
# creating 2 d array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholder in numpy arrays

In [13]:
# create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# create a array of particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
# create a numpy array with random values
b =  np.random.random((3,4))
print(b)

[[0.94010763 0.76235404 0.49549732 0.36265352]
 [0.70870876 0.86673811 0.52347194 0.95313696]
 [0.28143665 0.08669158 0.16153311 0.71986517]]


In [19]:
# random values array within the specific range
c = np.random.randint(10,100,(3,4))
print(c)

[[68 24 51 40]
 [81 44 99 83]
 [21 49 56 13]]


In [20]:
# create a array evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [21]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [22]:
# convert a list to a numpy array
list2 = [10,20,30,40]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40]


numpy.ndarray

Analysing a numpy array

In [24]:
c = np.random.randint(10,90,(5,5))
print(c)

[[74 32 45 82 39]
 [25 40 23 26 47]
 [36 73 85 62 81]
 [10 73 50 53 62]
 [39 66 68 14 54]]


In [25]:
# array dimension
print(c.shape)

(5, 5)


In [26]:
# number of dimensions
print(c.ndim)

2


In [27]:
# number of elements in array
print(c.size)

25


In [28]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operaton on numpy array

In [29]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
print(list1+list2) #concatenate the two lists

[1, 2, 3, 4, 5, 6, 7, 8]


In [30]:
a = np.random.randint(0,10,(3,3))
b= np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 3 3]
 [4 1 1]
 [1 3 7]]
[[13 16 10]
 [14 17 14]
 [13 18 18]]


In [31]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[14 19 13]
 [18 18 15]
 [14 21 25]]
[[-12 -13  -7]
 [-10 -16 -13]
 [-12 -15 -11]]
[[ 13  48  30]
 [ 56  17  14]
 [ 13  54 126]]
[[0.07692308 0.1875     0.3       ]
 [0.28571429 0.05882353 0.07142857]
 [0.07692308 0.16666667 0.38888889]]


In [32]:
a = np.random.randint(0,10,(3,3))
b= np.random.randint(10,20,(3,3))
print(a)
print(b)

[[2 0 0]
 [7 5 6]
 [4 2 8]]
[[15 10 16]
 [10 15 18]
 [12 16 12]]


In [33]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[17 10 16]
 [17 20 24]
 [16 18 20]]
[[-13 -10 -16]
 [ -3 -10 -12]
 [ -8 -14  -4]]
[[ 30   0   0]
 [ 70  75 108]
 [ 48  32  96]]
[[0.13333333 0.         0.        ]
 [0.7        0.33333333 0.33333333]
 [0.33333333 0.125      0.66666667]]


Array manipulation

In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 1 2]
 [9 4 7]]
(2, 3)


In [35]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 9]
 [1 4]
 [2 7]]
(3, 2)


In [36]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 9 0]
 [1 0 8]]
(2, 3)


In [37]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[8 1]
 [9 0]
 [0 8]]
(3, 2)


In [38]:
# reshaping array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 7 4]
 [7 0 3]]
(2, 3)


In [39]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[6 7]
 [4 7]
 [0 3]]
(3, 2)
